Repository YU-RentCar/yurentcar-fe-web-v2, pull requests merged in 2023-09, with the labels that each got.

#2 [Feat/#1] nav 컴포넌트 구현과 폰트, 색상 설정
  src/assets/Logo.png
  src/components/.gitkeep
  src/components/Nav/Nav.js
  src/components/Nav/NavContainer.js
  src/fonts/SUIT-Variable.ttf
  src/index.css
  src/recoil/.gitkeep
  src/recoil/userAtom.js
  tailwind.config.js
Labels: ✨ Feat

#6 [Chore/#4] figma 설정과 같은 커스텀 shadow 추가
  tailwind.config.js
Labels: 📐 Chore

#7 [Fix/#5] 네비게이션 디자인 수정
  src/components/Nav/Nav.js
Labels: 🔧 Fix

#9 [Fix/#8] 웹 폰트 굵기 수동 설정
  src/index.css
Labels: 🔧 Fix

#12 [Fix/#10] Nav 폰트 weight 변경
  src/components/Nav/Nav.js
Labels: 🔧 Fix

#14 [Fix/#13] Nav 컴포넌트 top-0 속성 추가
  src/components/Nav/Nav.js
Labels: 🔧 Fix

#18 [Feat/#17] 팝업에서 사용할 수 있는 기능들을 구현한 usePopUp 추가
  src/recoil/popUpInfoSelector.js
  src/utils/popUp/usePopUp.js
Labels: ✨ Feat

#19 [Feat/#11] 마이페이지 렌트 대기 예약 정보, 사용자 기본 정보 구현
  src/App.js
  src/assets/Car.png
  src/pages/MyPage/Alert.js
  src/pages/MyPage/AlertContainer.js
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/MyPageContainer.js
  src/pages/MyPage/components/Reservation.js
  src/pages/MyPage/components/ReservationContainer.js
  src/pages/MyPage/components/UserInfo.js
  src/pages/MyPage/components/UserInfoContainer.js
  src/recoil/alertAtom.js
  src/recoil/resvAtom.js
  src/recoil/userAtom.js
Labels: ✨ Feat

#21 [Fix] 닉네임 변경 시 Alert 처리 추가 구현
  src/pages/MyPage/components/UserInfo.js
Labels: 🔧 Fix

#24 [Chore/#23] 파일 구조 변경
  src/App.js
  src/components/Nav.js
  src/components/Nav/NavContainer.js
  src/pages/Home/HomeContainer.js
  src/popUp/.gitkeep
  src/utils/usePopUp.js
Labels: 📐 Chore

#25 [Feat/#22] 마이페이지 사용자 선호 차량 옵션, 면허 정보, 계정 관리 구현
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/Quit.js
  src/pages/MyPage/QuitContainer.js
  src/pages/MyPage/components/Account.js
  src/pages/MyPage/components/AccountContainer.js
  src/pages/MyPage/components/License.js
  src/pages/MyPage/components/LicenseContainer.js
  src/pages/MyPage/components/PreferOption.js
  src/pages/MyPage/components/PreferOptionContainer.js
  src/recoil/preferOptionAtom.js
  src/recoil/userAtom.js
Labels: ✨ Feat

#27 [Feat/#16] 지점 선택창의 지역, 지점 검색 추가
  package.json
  src/assets/Map.svg
  src/pages/Home/Home.js
  src/popUp/.gitkeep
  src/popUp/Home/SelectStore.js
  src/recoil/finderAtom.js
  src/recoil/storeAtom.js
  tailwind.config.js
  yarn.lock
Labels: ✨ Feat

#28 [Fix/#26] 파일 구조 변화로 인한 마이페이지 수정 및 보완
  src/App.js
  src/pages/MyPage/Account.js
  src/pages/MyPage/Alert.js
  src/pages/MyPage/AlertContainer.js
  src/pages/MyPage/License.js
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/MyPageContainer.js
  src/pages/MyPage/PreferContent.js
  src/pages/MyPage/PreferOption.js
  src/pages/MyPage/Quit.js
  src/pages/MyPage/QuitContainer.js
  src/pages/MyPage/Reservation.js
  src/pages/MyPage/UserContent.js
  src/pages/MyPage/UserInfo.js
  src/pages/MyPage/UserNickChange.js
  src/pages/MyPage/components/AccountContainer.js
  src/pages/MyPage/components/License.js
  src/pages/MyPage/components/LicenseContainer.js
  src/pages/MyPage/components/PreferOption.js
  src/pages/MyPage/components/PreferOptionContainer.js
  src/pages/MyPage/components/Reservation.js
  src/pages/MyPage/components/ReservationContainer.js
  src/pages/MyPage/components/UserInfo.js
  src/pages/MyPage/components/UserInfoContainer.js
  src/utils/useAlert.js
Labels: 🔧 Fix

#33 [Feat/#29] 마이페이지 사용자 이용 내역 구현
  src/components/CarCard.js
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/Record.js
  src/recoil/carAtom.js
  src/recoil/userAtom.js
Labels: ✨ Feat

#35 [Feat/#34] 마이페이지 각 내역 조회 별로 필요한 팝업 구현
  src/components/CarCard.js
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/Record.js
  src/pages/MyPage/ResvCard.js
  src/popUp/MyPage/Point.js
  src/popUp/MyPage/Resv.js
  src/popUp/MyPage/Review.js
  src/recoil/userAtom.js
Labels: ✨ Feat
