Repository YU-RentCar/yurentcar-fe-web-v2, pull requests merged in 2023-10, with the labels that each got.

#36 [Feat/#32] 날짜 시간 선택 팝업 추가
  package.json
  src/index.css
  src/pages/Home/Home.js
  src/popUp/Home/SelectDateTime.js
  src/popUp/Home/SelectStore.js
  src/recoil/finderAtom.js
  yarn.lock
Labels: ✨ Feat

#39 [Feat/#38] 예약페이지 차량 기본, 상세 정보 구현
  src/App.js
  src/pages/Reservation/DefaultInfo.js
  src/pages/Reservation/DetailInfo.js
  src/pages/Reservation/Reservation.js
  src/recoil/carAtom.js
Labels: ✨ Feat

#41 [Feat/#40] 예약 페이지 차량 수리, 사고 내역 구현
  src/pages/Reservation/Accident.js
  src/pages/Reservation/Repair.js
  src/pages/Reservation/Reservation.js
  src/recoil/carAtom.js
Labels: ✨ Feat

#44 [Fix/#43] 마이페이지 모든 컴포넌트 그림자 추가
  src/pages/MyPage/Account.js
  src/pages/MyPage/License.js
  src/pages/MyPage/PreferOption.js
  src/pages/MyPage/Record.js
  src/pages/MyPage/Reservation.js
  src/pages/MyPage/UserInfo.js
Labels: 🔧 Fix

#45 [Feat/#42] 예약 페이지 지점 지도, 차량 종합 보험 구현
  public/index.html
  src/pages/Reservation/Accident.js
  src/pages/Reservation/DetailInfo.js
  src/pages/Reservation/Insurance.js
  src/pages/Reservation/Map.js
  src/pages/Reservation/Repair.js
  src/pages/Reservation/Reservation.js
Labels: ✨ Feat

#47 [Fix/#37] 지점, 시간 선택 메뉴 공용 컴포넌트화
  src/components/Finder.js
  src/pages/Home/Home.js
  src/popUp/SelectDateTime.js
  src/popUp/SelectStore.js
Labels: 🔧 Fix

#49 [Feat/#46] 예약 페이지 운전자 등록, 포인트 사용, 최종 결제 구현
  src/pages/Reservation/Close.js
  src/pages/Reservation/Drivers.js
  src/pages/Reservation/Final.js
  src/pages/Reservation/Insurance.js
  src/pages/Reservation/Open.js
  src/pages/Reservation/Point.js
  src/pages/Reservation/Reservation.js
  src/recoil/rentAtom.js
Labels: ✨ Feat

#51 [Feat/#50] 소셜 로그인 구현
  src/App.js
  src/assets/Kakao.png
  src/assets/Naver.png
  src/pages/Auth/Auth.js
Labels: ✨ Feat

#53 [Feat/#52] 공지사항 리스트 구현
  src/App.js
  src/pages/Notice/Notice.js
  src/pages/Notice/NoticeCard.js
  src/recoil/noticeAtom.js
Labels: ✨ Feat

#57 [Feat/#48] 차량 검색 페이지 UI 구현
  src/App.js
  src/components/CarCard.js
  src/components/Finder.js
  src/pages/CarSearch/CarSearch.js
  src/pages/CarSearch/NoticeCarousel.js
  src/pages/CarSearch/PreferOption.js
  src/pages/Home/Home.js
  src/popUp/SelectDateTime.js
  src/popUp/SelectStore.js
Labels: ✨ Feat

#60 [Feat/#54] 공지사항 상세보기 구현
  src/App.js
  src/pages/NoticeDetail/NoticeDetail.js
Labels: ✨ Feat

#61 [Fix/#59] 공지사항 리스트 페이지 파인더 삭제
  src/pages/Notice/Notice.js
Labels: 🔧 Fix

#62 [Feat/#56] 차량 상세정보 팝업 UI 구현
  src/pages/CarSearch/CarSearch.js
  src/popUp/CarSearch/CarDetail.js
Labels: ✨ Feat

#64 [Feat/#63] 이전 레포지토리의 Axios 내용들을 모두 옮김
  src/api/.gitkeep
  src/api/detailAxios.js
  src/api/homeAxios.js
  src/api/interceptors.js
  src/api/myPageAxios.js
  src/api/reservationAxios.js
Labels: ✨ Feat

#66 [Chore/#65] 빌드와 배포 자동화를 위한 Github Actions 설정
  .github/workflows/tempDeploy.yml
Labels: 📐 Chore

#68 [Chore/#67] CI 옵션 수정
  .github/workflows/tempDeploy.yml
Labels: 📐 Chore

#70 [Chore/#69] 웹 서버와 url 동기화
  package.json
  src/App.js
  src/components/Nav.js
Labels: 📐 Chore

#72 [Fix/#71] 예약 페이지 차량 상세 정보 차량 크기 추가
  src/pages/Reservation/DetailInfo.js
  src/recoil/carAtom.js
Labels: 🔧 Fix

#75 [Chore/#74] 환경 변수 설정
  .github/workflows/tempDeploy.yml
  .gitignore
  src/api/interceptors.js
Labels: 📐 Chore

#76 [Feat/#73] 네이버 소셜 로그인
  .github/workflows/tempDeploy.yml
  src/pages/Auth/Auth.js
Labels: ✨ Feat

#80 [Feat/#77] 시작화면 지정 구현
  src/App.js
Labels: ✨ Feat

#82 [Chore/#81] 환경 변수로 인한 설정 변경
  .github/workflows/tempDeploy.yml
  package.json
  src/App.js
  src/api/interceptors.js
  src/index.js
  src/pages/Auth/Auth.js
  yarn.lock
Labels: 📐 Chore

#84 [Chore/#83] 리다이렉트 404 에러 수정
  .github/workflows/tempDeploy.yml
  package.json
  src/App.js
  src/components/Nav.js
Labels: 📐 Chore

#87 [Feat/#86] Nav 사용자 정보 불러오기 api 적용
  src/api/interceptors.js
  src/components/Nav.js
Labels: ✨ Feat

#89 [Feat/#88] 지도 팝업 api 연결
  src/popUp/SelectStore.js
  src/recoil/storeAtom.js
Labels: ✨ Feat

#93 [Feat/#90] finder 유효성 검사 추가
  src/components/Finder.js
  src/pages/CarSearch/CarSearch.js
  src/pages/Home/Home.js
Labels: ✨ Feat

#95 [Feat/#92] 마이페이지 사용 내역, 면허 정보, 계정 관리 api 구현
  .github/workflows/tempDeploy.yml
  src/App.js
  src/api/myPageAxios.js
  src/pages/MyPage/Account.js
  src/pages/MyPage/License.js
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/Record.js
  src/pages/MyPage/ResvCard.js
  src/popUp/MyPage/Point.js
  src/popUp/MyPage/Quit.js
  src/popUp/MyPage/Resv.js
  src/popUp/MyPage/Review.js
  src/recoil/reviewTargetAtom.js
Labels: ✨ Feat

#98 [Feat/#94] 차량 리스트 불러오기 api 연결
  src/components/CarCard.js
  src/components/Finder.js
  src/pages/CarSearch/CarSearch.js
Labels: ✨ Feat

#103 [Feat/#97] 로그인 체크 커스텀 훅 구현
  src/App.js
  src/pages/MyPage/MyPage.js
  src/recoil/navStateAtom.js
  src/utils/useAuth.js
Labels: ✨ Feat

#104 [Feat/#99] 사용자 선호 옵션 메뉴 api 연결
  src/components/Finder.js
  src/pages/CarSearch/CarSearch.js
  src/pages/CarSearch/PreferOption.js
  src/recoil/selectedFinderAtom.js
Labels: ✨ Feat

#107 [Feat/#96] 예약 페이지 차량 기본&상세 정보, 수리&사고 내역, 지점 지도 api 구현
  src/api/reservationAxios.js
  src/pages/Reservation/Accident.js
  src/pages/Reservation/DefaultInfo.js
  src/pages/Reservation/DetailInfo.js
  src/pages/Reservation/Map.js
  src/pages/Reservation/Repair.js
Labels: ✨ Feat

#108 [Feat/#100] carousel api 연결
  src/api/carSearchAxios.js
  src/pages/CarSearch/CarSearch.js
  src/pages/CarSearch/NoticeCarousel.js
Labels: ✨ Feat

#110 [Feat/#101] 최근 본 차량 로컬스토리지 저장
  src/pages/CarSearch/CarSearch.js
Labels: ✨ Feat

#113 [Feat/#102] 차량 상세정보 조회 팝업 api 연결
  src/api/carSearchAxios.js
  src/components/CarCard.js
  src/pages/CarSearch/CarSearch.js
  src/popUp/CarSearch/CarDetail.js
Labels: ✨ Feat

#114 [Feat/#105] 예약 페이지 운전자 등록, 포인트 사용, 최종 결제 api 구현
  src/api/reservationAxios.js
  src/pages/Reservation/DefaultInfo.js
  src/pages/Reservation/Drivers.js
  src/pages/Reservation/Final.js
  src/pages/Reservation/Open.js
  src/pages/Reservation/Point.js
  src/recoil/rentAtom.js
Labels: ✨ Feat

#116 [Fix/#109] 공지사항 리스트가 3개 미만에서 문제 생기는 것을 수정
  src/pages/CarSearch/CarSearch.js
  src/pages/CarSearch/NoticeCarousel.js
Labels: 🔧 Fix

#117 [Feat/#106] 마이페이지 후기 조회, 후기 작성 시 포인트 적립 사유 입력, 최근 본 차량 조회 api 구현
  src/api/myPageAxios.js
  src/pages/MyPage/Record.js
  src/popUp/MyPage/Review.js
Labels: ✨ Feat

#120 [Fix/#115] 닉네임 변경 시 nav의 사용자 정보가 즉시 변경되지 않던 문제를 수정
  src/components/Nav.js
  src/pages/MyPage/UserNickChange.js
  src/recoil/navNickNameAtom.js
Labels: 🔧 Fix

#121 [Feat/#119] 공지사항 api
  src/api/noticeAxios.js
  src/pages/CarSearch/CarSearch.js
  src/pages/CarSearch/NoticeCarousel.js
  src/pages/Notice/Notice.js
  src/pages/Notice/NoticeCard.js
  src/pages/NoticeDetail/NoticeDetail.js
Labels: ✨ Feat

#123 [Fix/#122] 예약 페이지 더미 데이터들 location state 로 수정
  src/pages/Reservation/Accident.js
  src/pages/Reservation/DefaultInfo.js
  src/pages/Reservation/DetailInfo.js
  src/pages/Reservation/Map.js
  src/pages/Reservation/Repair.js
Labels: 🔧 Fix

#124 [Fix/#112] finder가 새로고침하면 사라지는 문제 해결
  src/components/Finder.js
  src/pages/CarSearch/CarSearch.js
Labels: 🔧 Fix

#125 [Fix/#118] 차량 상세정보 블럭 크기가 이상해지는 문제 수정
  src/popUp/CarSearch/CarDetail.js
Labels: 🔧 Fix

#126 [Fix/#111] 차량 리스트의 카드가 보이는 것보다 큰 범위가 클릭되는 문제 수정
  src/pages/CarSearch/CarSearch.js
Labels: 🔧 Fix

#128 [Fix/#127] 예약 페이지 finder 연결, 새로고침 시 페이지 이동
  src/App.js
  src/pages/Reservation/DefaultInfo.js
Labels: 🔧 Fix

#131 [Fix/#129] 예약 화면에서 검색 클릭 시 아무런 정보 없는 cardetail로 가던 오류 수정
  src/popUp/CarSearch/CarDetail.js
Labels: 🔧 Fix

#133 [Fix/#132] 예약화면에서 리스트 화면으로 넘어갔을때 다른 카드 안눌리는 버그 수정
  src/pages/CarSearch/CarSearch.js
  src/popUp/CarSearch/CarDetail.js
Labels: 🔧 Fix

#134 [Fix/#130] 선호 옵션, 로컬스토리지 읽는 방식 수정
  src/pages/MyPage/Record.js
  src/recoil/preferOptionAtom.js
Labels: 🔧 Fix

#136 [Feat/#135] 서버로부터 차량 사진 받아와서 연결
  src/components/CarCard.js
  src/pages/MyPage/Reservation.js
  src/pages/MyPage/ResvCard.js
  src/pages/Reservation/DefaultInfo.js
  src/popUp/CarSearch/CarDetail.js
Labels: ✨ Feat
